INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (13, 'Can add content type', 4, 'add_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (14, 'Can change content type', 4, 'change_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (15, 'Can delete content type', 4, 'delete_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (16, 'Can view content type', 4, 'view_contenttype');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (17, 'Can add session', 5, 'add_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (18, 'Can change session', 5, 'change_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (19, 'Can delete session', 5, 'delete_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (20, 'Can view session', 5, 'view_session');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (21, 'Can add attendance', 6, 'add_attendance');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (22, 'Can change attendance', 6, 'change_attendance');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (23, 'Can delete attendance', 6, 'delete_attendance');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (24, 'Can view attendance', 6, 'view_attendance');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (25, 'Can add courses', 7, 'add_courses');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (26, 'Can change courses', 7, 'change_courses');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (27, 'Can delete courses', 7, 'delete_courses');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (28, 'Can view courses', 7, 'view_courses');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (29, 'Can add staffs', 8, 'add_staffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (30, 'Can change staffs', 8, 'change_staffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (31, 'Can delete staffs', 8, 'delete_staffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (32, 'Can view staffs', 8, 'view_staffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (33, 'Can add user', 9, 'add_customuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (34, 'Can change user', 9, 'change_customuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (35, 'Can delete user', 9, 'delete_customuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (36, 'Can view user', 9, 'view_customuser');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (37, 'Can add subjects', 10, 'add_subjects');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (38, 'Can change subjects', 10, 'change_subjects');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (39, 'Can delete subjects', 10, 'delete_subjects');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (40, 'Can view subjects', 10, 'view_subjects');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (41, 'Can add students', 11, 'add_students');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (42, 'Can change students', 11, 'change_students');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (43, 'Can delete students', 11, 'delete_students');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (44, 'Can view students', 11, 'view_students');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (45, 'Can add notification student', 12, 'add_notificationstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (46, 'Can change notification student', 12, 'change_notificationstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (47, 'Can delete notification student', 12, 'delete_notificationstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (48, 'Can view notification student', 12, 'view_notificationstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (49, 'Can add notification staffs', 13, 'add_notificationstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (50, 'Can change notification staffs', 13, 'change_notificationstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (51, 'Can delete notification staffs', 13, 'delete_notificationstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (52, 'Can view notification staffs', 13, 'view_notificationstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (53, 'Can add leave report student', 14, 'add_leavereportstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (54, 'Can change leave report student', 14, 'change_leavereportstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (55, 'Can delete leave report student', 14, 'delete_leavereportstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (56, 'Can view leave report student', 14, 'view_leavereportstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (57, 'Can add leave report staff', 15, 'add_leavereportstaff');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (58, 'Can change leave report staff', 15, 'change_leavereportstaff');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (59, 'Can delete leave report staff', 15, 'delete_leavereportstaff');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (60, 'Can view leave report staff', 15, 'view_leavereportstaff');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (61, 'Can add feedback student', 16, 'add_feedbackstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (62, 'Can change feedback student', 16, 'change_feedbackstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (63, 'Can delete feedback student', 16, 'delete_feedbackstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (64, 'Can view feedback student', 16, 'view_feedbackstudent');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (65, 'Can add feedback staffs', 17, 'add_feedbackstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (66, 'Can change feedback staffs', 17, 'change_feedbackstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (67, 'Can delete feedback staffs', 17, 'delete_feedbackstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (68, 'Can view feedback staffs', 17, 'view_feedbackstaffs');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (69, 'Can add attendance report', 18, 'add_attendancereport');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (70, 'Can change attendance report', 18, 'change_attendancereport');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (71, 'Can delete attendance report', 18, 'delete_attendancereport');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (72, 'Can view attendance report', 18, 'view_attendancereport');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (73, 'Can add admin ho d', 19, 'add_adminhod');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (74, 'Can change admin ho d', 19, 'change_adminhod');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (75, 'Can delete admin ho d', 19, 'delete_adminhod');
INSERT INTO public.auth_permission (id, name, content_type_id, codename) VALUES (76, 'Can view admin ho d', 19, 'view_adminhod');