# Generated by Django 3.1.2 on 2020-10-15 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StdMgtApp', '0002_auto_20200917_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='StdMgtApp.courses'),
        ),
    ]
