# Generated by Django 3.1.2 on 2020-12-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StdMgtApp', '0002_auto_20201222_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavereportstaff',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
